### ISSUE TITLE
Item carousel with percentage width

### ISSUE THREAD

**Issue by 1ud0v1c** [Pixplicity/MultiViewPager#17]
Hi, 
First of all, thank you for your hard work :).
The thing is, I'm currently trying to create a carousel thanks to a ViewPager. I succeed to make a multiviewpager but by using a tricky solution : 

```
root.post(new Runnable() {
            @Override
            public void run() {
                CarouselViewPager carousel = (CarouselViewPager) getActivity().findViewById(R.id.carousel);
                int width = root.getWidth();
                int paddingWidth = (int) (width * 0.22);
                root.setPadding(paddingWidth, 0, paddingWidth, 0);
                root.getLayoutParams().width = width-(paddingWidth*2);
                root.requestLayout();

                carousel.setPageMargin(-(paddingWidth-8)*2);
            }
        });
```

I saw in your sample that you set a fixed width (200dp), is it possible with your solution, to have a child item with ie : 50% of the width of the ViewPager ? Regards.

**Comment by pflammertsma** [comment]
The behavior of setting a proportional page width is actually included in the ViewPager itself; you don't need MultiViewPager for this purpose.

In your PagerAdapter, override the following method:

```
@Override
public float getPageWidth(int position) {
    return 0.8f;
}
```

The documentation for `getPageWidth()` reads:

> Returns the proportional width of a given page as a percentage of the ViewPager's measured width from (0.f-1.f]

Does this answer your question?

**Comment by 1ud0v1c** [comment]
Sorry I took many times to answer. The problem with the solution you propose, it's you can't center your item. He will have a little shift, that's annoying. But I succeed to keep my solutions with the padding and have the touch event I wanted. The solution was easy, just apply my touch event on the children of my item viewpager layout and that's it. Anyway, thanks for your time and consideration.
