### ISSUE TITLE
Left-alignment of pages

### ISSUE THREAD

**Issue by laaptu** [Pixplicity/MultiViewPager#2]
Thanks a million for this awesome library.

I need to make some changes in this library to achieve the following effect:
1. When there is only one item on pager, the item must be centered:  
   ![screen shot 2015-02-12 at 3 31 23 pm](https://cloud.githubusercontent.com/assets/97506/6199325/412274be-b465-11e4-9297-01e2cbeac9bf.png)
2. When there are more than one item, the initial screen should be like this:  
   ![screen shot 2015-02-12 at 3 37 40 pm](https://cloud.githubusercontent.com/assets/97506/6199328/54ad5a76-b465-11e4-8792-88ea33410531.png)
3. When the user scrolls the pages( items greater than 1), each selected page now will be centered like this:  
   ![screen shot 2015-02-14 at 4 20 52 pm](https://cloud.githubusercontent.com/assets/97506/6199340/a89a44a0-b465-11e4-81d4-d6aa934eb64c.png)

I have achieved such effect by using two kind of `layout` on `PagerAdapter`
1. View with `layoutCenterInParent`
2. Other View having same content as 1 but no `layoutCenterInParent`
   
   On `PagerAdapter`, I have made following changes

``` Java
//Use this layout to inflate on instantiateItem
private int getLayoutId(int position) {
  int layoutId = getCount() > 1 ? R.layout.item_video :  
                         R.layout.item_video_center;
  return layoutId;
}
//call this method when page changes from 0 to 1 and vice versa
public boolean changeToCenter(int position) {
  if (getCount() > 1) {
    if (position == 0 && layoutId == R.layout.item_video_center) {
        layoutId = R.layout.item_video;
        notifyDataSetChanged();
        return true;
    } else if (layoutId == R.layout.item_video) {
        layoutId = R.layout.item_video_center;
        notifyDataSetChanged();
        return true;
    }
  }
  return false;
}
```

And on `onPageChangeListener` on `MultiViewPager`, I have made following changes

``` Java
@Override
public void onPageSelected(int i) {
  boolean smoothScroll = ((VideoItemPagerAdapter) adapter).changeToCenter(i);
  if (smoothScroll)
    scrollToPosition(i);
}

private void scrollToPosition(final int i) {
  new Handler().postDelayed(new Runnable() {
    @Override
    public void run() {
      pager.setCurrentItem(i, true);
    }
  }, 0);
}
```

This logic gives me my desired effect but on page change from 0 to 1 and vice versa the ViewPager stutters, due to layout changes. Further, this process is resource intensive during page change from 0 to 1 and vice versa. So any smart way I can do this. Your logic or hint would be more than enough.

**Comment by pflammertsma** [comment]
Very interesting, thanks for your feedback. I'm not sure that this behavior is so generic that it justifies including the logic within MultiViewPager itself.

I don't have any specific comments on your approach as I'd really have to sit down and think on it, but perhaps a more generic approach would be to make use of MultiViewPager's existing mechanism for aligning pages. This would perhaps be more efficient over swapping layouts through `notifyDataSetChanged()`.

I'd want to come back to this when I have a little more time.

**Comment by laaptu** [comment]
@pflammertsma  Thanks a lot for your comments. I am also looking for possible solutions and if it comes, I will post it here.
Above all , thanks again for this library

**Comment by pflammertsma** [comment]
I don't believe that a ViewPager is the ideal view for this behavior, as it specifically expects views to be centered; after all, the name suggests it navigates page by page.

How would the pager behave if the next view is only partly visible? I'm having difficulties imagining what a sensible user experience would be like if the pager abruptly stopped scrolling without centering the selected page.

Feedback welcome!

**Comment by pflammertsma** [comment]
You may have better luck not using MultiViewPager at all, but simply setting the PagerAdapter's page width by implementing `getPageWidth(int position)`. It may not give you the degree of granularity in setting the exact dimension of the page, but it does collapse the edge padding to achieve your desired effect.

I've taken a bit of time today to see if there's some way to get both mechanisms working by setting the page width dynamically to the computed page size, but due to the order in which calls are made in ViewPager, and the limited visibility of some required methods, I didn't manage to get it working, even with reflection.

If you want to go down that road, I'd suggest instead taking the source of ViewPager and adapting it precisely to your needs.
