### ISSUE TITLE
Endless viewpager

### ISSUE THREAD

**Issue by bojanvu23** [Pixplicity/MultiViewPager#20]
Hi,

Thank you for this, it's really great, but is there easy way to make Endless MultiViewPager?

Thanks,
Bojan

**Comment by pflammertsma** [comment]
You can simply set the size of your FragmentStatePagerAdapter to be Integer.MAX_VALUE and set the initial start index to be half of that. The amount of time the user would be swiping to reach the edge of the adapter would literally be billions of seconds.
