### ISSUE TITLE
Fragments not visible on Scrolling to the END 

### ISSUE THREAD

**Issue by peter1408** [Pixplicity/MultiViewPager#21]
i have  this viewpager implemented , but if the viewpager has large number of items , and if we scroll to one end and move back then the middle items of the viewpager are getting invisible .

**Comment by pflammertsma** [comment]
Are you using fragments or views? Which adapter is attached? Can you
provide a minimum working example of the issue?

**Comment by peter1408** [comment]
am using Fragments , and for the adapter am using FragmentStatePagerAdapter
am dynamically adding fragments to the adapter , they get added  to the adapter correctly all is working fine , but the issue is these fragments gets invisible on scrolling to the ends , 

if you have 1 to 10 fragments with buttons in it , then on reaching the 10th fragment the 2-5 fragments gets invisible but the button click for 2-5 fragments are working even though the view is not visible

**Comment by peter1408** [comment]
i guess its my adapter which is not able to handle  it , not the Viewpager class u have written , ur class is working good

**Comment by pflammertsma** [comment]
I'm glad you sorted it out.
