### ISSUE TITLE
multiview pager error 

### ISSUE THREAD

**Issue by engr-erum** [Pixplicity/MultiViewPager#23]
Process: com.example.abc.fragmentsapplication, PID: 8443
                                                                                           java.lang.NullPointerException: MatchWithChildResId did not find that ID in the first fragment of the ViewPager; is that view defined in the child view's layout? Note that MultiViewPager only measures the child for index 0.

**Comment by raj4vedi** [comment]
You have to add matchChildWidth in MultiViewPager, in xml
app:matchChildWidth="@+id/parent_id_of_child"

here parent_id_of_child will be child fragment or view id.
it fixed the issue for me.
