### ISSUE TITLE
Content of view is streached

### ISSUE THREAD

**Issue by raj4vedi** [Pixplicity/MultiViewPager#24]
I am using this library to showing cards with images and some other content. but the problem is that when I set card's width and height to desired, the content of the card is stretched. Please tell me the solution.

**Comment by pflammertsma** [comment]
Can you please provide a code snippet?

It sounds to me like an ordinary layout problem that isn't specifically
related to ViewPagers. Can you try wrapping your ImageView (or whichever
child view you're using) in a FrameLayout to see if the problem persists?
