### ISSUE TITLE
Enhance this feature to be more facebook like interaction.

### ISSUE THREAD

**Issue by jjhesk** [Pixplicity/MultiViewPager#4]
I have been thinking deep into library and I am trying to make it possible to animate like facebook.

When  I tap in the middle picture it will able to zoom into fullscreen. As fullscreen, it takes the width of  current selected image in the center and release the bounce to the screen width and the background turns dark. Is that possible achieve this effect?

**Comment by pflammertsma** [comment]
I don't believe this falls within the scope of the library. I would instead suggest turning to transitions; launch a new (translucent) Activity and provide the ImageView as a transition into it.
