### ISSUE TITLE
Unsusual behaviour with if number of elements more than 5?

### ISSUE THREAD

**Issue by umesh7715** [Pixplicity/MultiViewPager#6]
If number of elements in the list greater than 5 then Fragment view pager has the wired behavior as last element of the list gets hide on scrolling till end.

Maybe some hard coded values.

**Comment by pflammertsma** [comment]
I cannot reproduce this, but I don't think I understand the issue completely.

Can you provide a snippet or a more details to reproduce?

**Comment by umesh7715** [comment]
Thanks for replying.

I will revert back to you tomorrow once I reached office.

**Comment by umesh7715** [comment]
Can you try and change the FragmentStatePagerAdapter's getCount() method to change and return a number greater than 5 in PagerActivity? And check if behavior is normal when we swipe till last element and to first element in reverse order. Whether last element is hiding on sliding till last element.

**Comment by pflammertsma** [comment]
I've tried changing the count from 4 to 40, and all still works as expected. Can you explain what you mean with "last element is hiding on sliding till last element"?

Perhaps a few screenshots will help clarify?

**Comment by umesh7715** [comment]
Hi,
  Take up this scenario,

 Have 6 distinct images in array of resource. Then scroll right till the
end till last image appear in center, then start scrolling toward left side
see if centered image is same as what it should be.

 Also try scrolling till extreme left after above process and see if first
image is same as that in resource index array?

Let me know if i am still unclear to you. Thanks for replying :)

**Comment by pflammertsma** [comment]
I haven't tried this with images, but have adapted the sample with 25 pages of PageFragments, which now show their page numbers.

It sounds to me that your adapter is confusing items. How are you instantiating fragments and passing arguments into your fragments?

**Comment by umesh7715** [comment]
Got the source of the issue,

 It is happening when  fragments to left or right (hidden when scrolled)
were get recycled due to listview implementation. Actually my
implementation in such a way that center fragment get highlighted and all
other fragments states get restored to original and problem accrued during
restoring those fragment which were hidden.

 This problematic situation because i try to get all child views of
multiviewpager and highlight the centered fragment. But while getting all
childview from multiviewpager we can only get some of them which are not
recycled and we try to _restore it by index_ hence the issue.

 Thanks for your valuable time given for the issue. Any further
help/suggestion regarding my issue is appreciated.

**Comment by pflammertsma** [comment]
Good to know you got to the root of the problem.

It sounds to me that your ViewPager is making assumptions of what is displaying based on its child view count. I'm afraid I don't have the code in front of me (on mobile), but I would suggest adding a page change listener to the ViewPager and obtain the current page index. Use that moment as a trigger to inform any attached fragments that the page selection has changed, e.g. introducing an interface with onPageSelected() and calling it for the fragment with the aforementioned index, and onPageUnselected() for all other fragments present in the ViewPager.

Hope this helps!

**Comment by umesh7715** [comment]
Yes certainly give a try :)
