### ISSUE TITLE
Dragging from penultimate page to the last jumps back to the prior in the sample app

### ISSUE THREAD

**Issue by laomo** [Pixplicity/MultiViewPager#8]

**Comment by pflammertsma** [comment]
I see what you mean. In the sample app, when held in landscape and page 18 is showing, dragging to page 20 causes the pager to jump back to 19.

This is irregular, as skipping pages by twos is possible for all but the last page.

**Comment by pflammertsma** [comment]
The earliest I'll be able to look into this is Friday.

**Comment by laomo** [comment]
@pflammertsma Thanks

**Comment by pflammertsma** [comment]
It appears to be a bug in ViewPager.

The ACTION_UP MotionEvent doesn't account for margins; see: https://github.com/android/platform_frameworks_support/blob/master/v4/java/android/support/v4/view/ViewPager.java#L2012

The equation there should be similar to the one in `pageScrolled()`: https://github.com/android/platform_frameworks_support/blob/master/v4/java/android/support/v4/view/ViewPager.java#L1649

This appears to be related to an old bug we had filed in support-v4 that was removed as obsolete and never fixed. I'll file (another) bug in the hopes that it won't be ignored this time around.

In the meantime, I've forked the ViewPager to [apply this fix in a separate branch](https://github.com/Pixplicity/MultiViewPager/tree/forked-viewpager), but it means that the all logic for the ViewPager is now extracted into the MultiViewPager and any future updates to the support-v4 ViewPager will need to be included manually.

**Comment by pflammertsma** [comment]
For posterity, here are the issues in support-v4: [original issue #74032](https://code.google.com/p/android/issues/detail?id=74032) and [newly submitted issue #181864](https://code.google.com/p/android/issues/detail?id=181864).

I'm afraid either you'll have to maintain ViewPager yourself with the patch, or keep your fingers crossed that Google addresses the problem.

**Comment by laomo** [comment]
@pflammertsma It's unfortunate, but thank you very much.

**Comment by pflammertsma** [comment]
This issue is now being tracked as [support-v7 issue #203816](https://code.google.com/p/android/issues/detail?id=203816) as both previous issues have been marked as "obsolete" by Google.

**Comment by pflammertsma** [comment]
Great news! The bug in support-v7 should be resolved soon, which should in turn resolve this issue.

**Comment by pflammertsma** [comment]
The underlying issue from the Android support library causing this bug has been resolved:
http://code.google.com/p/android/issues/detail?id=203816
